---
- name: Install PowerShell 7 and update SSH shell
  # delegate_to: "{{ ec2_instance_info.public_ip }}"
  block:
    - name: Create Temp directory if it does not exist
      ansible.windows.win_file:
        path: C:\Temp
        state: directory

    - name: Download PowerShell 7 installer
      ansible.windows.win_get_url:
        url: "https://github.com/PowerShell/PowerShell/releases/download/v7.4.3/PowerShell-7.4.3-win-x64.msi"
        dest: C:\Temp\PowerShell-7.4.3-win-x64.msi

    - name: Install PowerShell 7
      ansible.windows.win_package:
        path: C:\Temp\PowerShell-7.4.3-win-x64.msi
        state: present

    - name: Update DefaultShell to PowerShell 7
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: 'C:\Program Files\PowerShell\7\pwsh.exe'
        type: string

    - name: Clean up PowerShell installer
      ansible.windows.win_file:
        path: C:\Temp\PowerShell-7.4.3-win-x64.msi
        state: absent
