---
# Manage EC2 key pair for SSH access and publish facts for later tasks

- name: Expand local SSH key paths
  ansible.builtin.set_fact:
    provision_private_key_path_expanded: "{{ provision_private_key_path | regex_replace('^~', lookup('env', 'HOME')) }}"
    provision_public_key_path_expanded: "{{ provision_public_key_path | regex_replace('^~', lookup('env', 'HOME')) }}"

- name: Ensure SSH key directory exists
  ansible.builtin.file:
    path: "{{ provision_private_key_path_expanded | dirname }}"
    state: directory
    mode: '0700'
  delegate_to: "{{ provision_control_host }}"
  run_once: true

- name: Generate EC2 key pair
  ansible.builtin.shell: |
    umask 0177
    ssh-keygen -t {{ ec2_ssh_key_type }} \
      -b {{ ec2_ssh_key_bits }} \
      -m PEM \
      -f "{{ provision_private_key_path_expanded }}" \
      -N "" \
      -C "ansible-generated-{{ ec2_key_name }}"
  delegate_to: "{{ provision_control_host }}"
  changed_when: false
  run_once: true

- name: Read public key content
  ansible.builtin.slurp:
    src: "{{ provision_public_key_path_expanded }}"
  register: public_key_content
  delegate_to: "{{ provision_control_host }}"
  run_once: true

- name: Read private key content for Vault storage
  ansible.builtin.slurp:
    src: "{{ provision_private_key_path_expanded }}"
  register: private_key_content
  delegate_to: "{{ provision_control_host }}"
  run_once: true

- name: Assemble key pair facts
  ansible.builtin.set_fact:
    ec2_keypair_info:
      key_name: "{{ ec2_key_name }}"
      key_fingerprint: "{{ ec2_keypair_result.key.fingerprint | default('') }}"
      public_key: "{{ public_key_content.content | b64decode if public_key_content is defined else '' }}"
      private_key: "{{ private_key_content.content | b64decode if private_key_content is defined else '' }}"
      key_type: "{{ ec2_ssh_key_type }}"
      key_bits: "{{ ec2_ssh_key_bits }}"
  delegate_to: "{{ provision_control_host }}"
  run_once: true

- name: Import key pair into AWS
  amazon.aws.ec2_key:
    name: "{{ ec2_key_name }}"
    key_material: "{{ ec2_keypair_info.public_key }}"
    state: present
    region: "{{ aws_region }}"
    tags:
      Name: "{{ ec2_key_name }}"
      Environment: "{{ ec2_environment }}"
      Project: "{{ ec2_project }}"
      ManagedBy: ansible
      CreatedBy: "{{ ansible_user | default('ansible') }}"
      CreatedAt: "{{ ansible_date_time.iso8601 }}"
  register: ec2_keypair_result
  delegate_to: "{{ provision_control_host }}"
  run_once: true

- name: Show key pair status
  ansible.builtin.debug:
    msg:
      - "EC2 key pair: {{ ec2_key_name }}"
      - "Fingerprint: {{ ec2_keypair_info.key_fingerprint | default('N/A') }}"
      - "Public key length: {{ ec2_keypair_info.public_key | length }}"
      - "Key ready for instance launch"
