---
# Entry point for provision_ec2 role.  Tasks are organised to validate inputs,
# build derived context, provision infrastructure, and persist metadata.

- name: Validate provisioning inputs
  ansible.builtin.import_tasks: validate.yml
  tags: ['provision', 'validation']

- name: Build provisioning context
  ansible.builtin.import_tasks: context.yml
  tags: ['provision', 'context']

- name: Discover AWS networking defaults
  ansible.builtin.import_tasks: discover.yml
  tags: ['provision', 'discovery']

- name: Manage SSH key pair
  ansible.builtin.import_tasks: keypair.yml
  tags: ['provision', 'keypair']

- name: Ensure security group exists
  ansible.builtin.import_tasks: security_group.yml
  tags: ['provision', 'security_group']

- name: Launch and wait for EC2 instance
  ansible.builtin.import_tasks: instance.yml
  tags: ['provision', 'instance']

- name: Manage Elastic IP association
  when: provision_allocate_eip | bool
  ansible.builtin.import_tasks: elastic_ip.yml
  tags: ['provision', 'network', 'elastic_ip']

- name: Configure Route53 record
  when: provision_configure_route53 | bool
  ansible.builtin.import_tasks: route53.yml
  tags: ['provision', 'route53']

- name: Store SSH key material in Vault
  ansible.builtin.import_tasks: vault_store_ssh.yml
  tags: ['provision', 'vault']

- name: Publish Windows custom facts
  when: provision_set_custom_facts | bool
  ansible.builtin.import_tasks: facts.yml
  tags: ['provision', 'facts']

- name: Display provisioning summary
  ansible.builtin.import_tasks: summary.yml
  tags: ['provision', 'results']
