---
# Create Route53 DNS A record for the EC2 instance

- name: Create Route53 A record for instance
  amazon.aws.route53:
    state: present
    hosted_zone_id: "{{ route53_zone_id }}"
    record: "{{ route53_effective_record_name }}"
    type: "{{ route53_record_type }}"
    value: "{{ ec2_instance_info.public_ip }}"
    ttl: {{ route53_record_ttl }}
    wait: true
    wait_timeout: 300
  register: route53_result
  delegate_to: "{{ provision_control_host }}"
  run_once: true

- name: Verify immediate DNS resolution
  ansible.builtin.command: "nslookup {{ route53_effective_record_name }}"
  register: dns_check
  changed_when: false
  failed_when: false
  delegate_to: "{{ provision_control_host }}"
  run_once: true

- name: Wait for DNS propagation
  ansible.builtin.command: "nslookup {{ route53_effective_record_name }}"
  register: dns_propagation_check
  retries: "{{ route53_dns_check_retries }}"
  delay: "{{ route53_dns_check_delay }}"
  until: dns_propagation_check.rc == 0
  changed_when: false
  ignore_errors: true
  delegate_to: "{{ provision_control_host }}"
  run_once: true
  when: route53_wait_for_propagation | bool

- name: Store Route53 information
  set_fact:
    route53_info:
      record_name: "{{ route53_effective_record_name }}"
      record_type: "{{ route53_record_type }}"
      record_value: "{{ ec2_instance_info.public_ip }}"
      ttl: "{{ route53_record_ttl }}"
      hosted_zone_id: "{{ route53_zone_id }}"
      status: "{{ 'created' if route53_result.changed else 'exists' }}"
      dns_check: "{{ 'resolved' if dns_check.rc == 0 else 'pending' }}"

- name: Tag instance with DNS information
  amazon.aws.ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ ec2_instance_info.instance_id }}"
    tags:
      FQDN: "{{ route53_effective_record_name }}"
      DNSConfigured: "{{ (dns_check.rc == 0) | ternary('true', 'pending') }}"
      DNSCreatedAt: "{{ ansible_date_time.iso8601 }}"
  delegate_to: "{{ provision_control_host }}"
  run_once: true

- name: Show Route53 record details
  ansible.builtin.debug:
    msg:
      - "Route53 record {{ route53_info.status }}"
      - "  FQDN: {{ route53_info.record_name }}"
      - "  Value: {{ route53_info.record_value }}"
      - "  DNS check: {{ route53_info.dns_check | upper }}"
