---
- name: Build Vault payload for SSH secret
  ansible.builtin.set_fact:
    provision_vault_payload:
      instance_id: "{{ ec2_instance_info.instance_id | default('') }}"
      instance_type: "{{ ec2_instance_info.instance_type | default('') }}"
      image_id: "{{ ec2_instance_info.image_id | default('') }}"
      region: "{{ ec2_instance_info.availability_zone | default(aws_region) }}"
      private_ip: "{{ ec2_instance_info.private_ip | default('') }}"
      public_ip: "{{ ec2_instance_info.public_ip | default('') }}"
      key_name: "{{ ec2_instance_info.key_name | default('') }}"
      security_group_id: "{{ ec2_security_group_id | default('') }}"
      security_group_name: "{{ ec2_security_group_name | default('') }}"
      vpc_id: "{{ aws_vpc_id | default('') }}"
      private_key: "{{ ec2_keypair_info.private_key | default('') }}"
      admin_password: "{{ windows_admin_password }}"

- name: Store SSH secret
  ansible.builtin.include_role:
    name: manage_secret
  vars:
    manage_secret_action: write
    manage_secret_payload: "{{ provision_vault_payload }}"
    manage_secret_path: "windows/{{ ec2_name_tag }}"
  register: provision_ec2_vault_write_result

- name: Debug write result
  ansible.builtin.debug:
    var: provision_ec2_vault_write_result
  when: "provision_ec2_vault_write_result is defined"

- name: Verify stored SSH secret
  ansible.builtin.include_role:
    name: manage_secret
  vars:
    manage_secret_action: get
    manage_secret_path: "windows/{{ ec2_name_tag }}"
