---
# Tag the root EBS volume for easier identification

- name: Tag root EBS volume
  amazon.aws.ec2_tag:
    region: "{{ aws_region }}"
    resource: "{{ ec2_instance_info.root_volume_id }}"
    state: present
    tags:
      Name: "{{ ec2_root_volume_name }}"
      InstanceId: "{{ ec2_instance_info.instance_id }}"
      ManagedBy: ansible
      CreatedAt: "{{ ansible_date_time.iso8601 }}"
      Project: "{{ ec2_project }}"
      Environment: "{{ ec2_environment }}"
  delegate_to: "{{ provision_control_host }}"
  run_once: true
  when:
    - provision_tag_root_volume | bool
    - ec2_instance_info.root_volume_id | default('') | length > 0
