---
- name: Job 1
  gather_facts: false
  hosts: aws_ec2
  tasks:
    - name: Get computer name
      ansible.windows.win_shell:
        $env:COMPUTERNAME
      register: cn_cmd

    - name: Set stats for later
      ansible.builtin.set_stats:
        cn: "{{ cn_cmd.stdout }}"
