---
- name: Provision EC2 instance
  hosts: localhost
  roles:
    - role: provision_ec2

  post_tasks:
    - name: Expose EC2 IP to workflow
      ansible.builtin.set_stats:
        data:
          provisioned_host: "{{ ec2_name_tag }}"
          provisioned_sg_id: "{{ security_group_result.group_id }}"
          aws_region: "{{ aws_region }}"
          vpc_id: "{{ vpc_id }}"
