---
# Playbook: Provision a Windows EC2 instance with Vault-backed SSH storage
# Usage: ansible-playbook -i localhost, 01_provision_ec2.yml

- name: Provision Windows EC2 instance with SSH access
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - role: provision_ec2
      vars:
        vault_auth_mount_point: approle
        vault_ssh_path: "windows/ssh/{{ ec2_name_tag }}"
