---
- name: Install SQL Server on Windows
  hosts: aws_ec2
  gather_facts: false

  vars:
    sql_version: "{{ sql_server_version | default('2022') }}"
    sql_edition: "{{ sql_server_edition | default('Express') }}"
    sql_sa_password: "{{ vault_sa_password }}"
    sql_port: "{{ sql_server_port | default(1433) }}"

  roles:
    - install_sql_server
