---
- name: Install SQL Server on Windows
  hosts: "{{ host }}"
  gather_facts: false
  vars:
    mssql_version: "{{ sql_server_version | default('2022') }}"
    mssql_database_edition: "{{ sql_server_edition | default('Express') }}"
    sql_s3_bucket: "alloy-software-installers"
    sql_s3_object: "SQL{{ mssql_version }}.zip"
    sql_s3_url_expiry: 3600
    sql_install_temp_dir: C:\temp
    host: "{{ provisioned_host | default('aws_ec2') }}"

  pre_tasks:

    - name: Get host connection details
      delegate_to: localhost
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details

    - name: Gather facts
      ansible.builtin.gather_facts:

    - name: Share group ID
      ansible.builtin.set_fact:
        security_group_id: "{{ provisioned_sg_id if provisioned_sg_id is defined else hostvars[host]['security_groups'][0]['group_id'] }}"

    - name: Determine S3 region for installer
      ansible.builtin.set_fact:
        sql_s3_region_effective: >-
          {{ hostvars[inventory_hostname].placement.region }}

    - name: Generate installer presigned URL
      delegate_to: localhost
      amazon.aws.s3_object:
        mode: geturl
        bucket: "{{ sql_s3_bucket }}"
        object: "{{ sql_s3_object }}"
        expiry: "{{ sql_s3_url_expiry }}"
        region: "{{ sql_s3_region_effective }}"
      register: sql_installer_url

    - name: Share url
      delegate_to: localhost
      ansible.builtin.set_fact:
        sql_installer_url: "{{ sql_installer_url.url }}"

    - name: Set PID based on edition only if not already defined
      ansible.builtin.set_fact:
        pid: "{{
            {
            'evaluation': '00000-00000-00000-00000-00000',
            'express': '11111-00000-00000-00000-00000',
            'developer': '22222-00000-00000-00000-00000'}[sql_server_edition] }}"
      when: pid is not defined or pid | trim == ""

    - name: Set shell type to pwsh.exe
      ansible.builtin.set_fact:
        ansible_shell_type: powershell

    - name: Download SQL Server bootstrapper
      ansible.windows.win_get_url:
        url: "{{ sql_installer_url }}"
        dest: "{{ sql_install_temp_dir }}\\{{ sql_s3_object }}"
      register: sql_download_result

    - name: Unzip installer
      community.windows.win_unzip:
        src: "{{ sql_install_temp_dir }}\\{{ sql_s3_object }}"
        dest: "{{ sql_install_temp_dir }}\\unzipped"
        delete_archive: true

  roles:
    - role: trippsc2.mssql.install
      vars:
        mssql_sqm_reporting: false
        mssql_error_reporting: false
        mssql_install_database_engine: true
        mssql_install_full_text: true
        mssql_version: "{{ sql_server_version | default('2022') }}"
        mssql_database_edition: "{{ sql_server_edition | default('Express') }}"
        mssql_configure_firewall: false
        mssql_install_agent: false
        mssql_port: 51967
        mssql_security_mode: mixed
        mssql_product_key: "{{ pid }}"
        mssql_sa_password: "{{ sql_sa_password }}"
        mssql_setup_path: "{{ sql_install_temp_dir }}\\unzipped\\SQL2022"
        mssql_update_enabled: false
        mssql_update_from_microsoft_update: false
        mssql_named_pipes_enabled: true
        mssql_tcp_enabled: true
        mssql_sql_server_service_startup_type: Automatic
        mssql_install_sql_server_management_studio: false
        mssql_database_sysadmin_accounts:
          - Administrator


  post_tasks:
    - name: Stop SQL Server service
      ansible.windows.win_service:
        name: MSSQLSERVER
        state: stopped
      failed_when: false

    - name: Get SQL Server instance name
      ansible.windows.win_shell: |
        $regPath = "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server"
        Get-ChildItem $regPath |
        Where-Object {$_.PSChildName -like "MSSQL*.*"} |
        Select-Object -ExpandProperty PSChildName
      register: sql_instance

    - name: Extract Name
      ansible.builtin.set_fact:
        sql_isntance_name: "{{ sql_instance.stdout_lines[0] }}"

    - name: Change SQL Server port in registry
      ansible.windows.win_regedit:
        path: "HKLM:\\SOFTWARE\\Microsoft\\Microsoft SQL Server\\{{ sql_isntance_name }}\\MSSQLServer\\SuperSocketNetLib\\Tcp\\IPAll"
        name: TcpPort
        data: "{{ sql_server_port }}"
        type: string
        state: present

    - name: Start SQL Server service
      ansible.windows.win_service:
        name: MSSQLSERVER
        state: started
      failed_when: false

- name: Open SQL Server Port
  hosts: localhost
  gather_facts: false

  roles:
    - role: add_ingress_rules
      vars:
        new_inbound_rules:
          - proto: tcp
            ports: ["{{ sql_server_port }}"]
            cidr_ip: "0.0.0.0/0"
            rule_desc: "SQL Server Access"
        sg_id: "{{ provisioned_sg_id }}"
