- name: Migrate databases
  hosts: localhost
  vars:
    source: ""
    dest: ""
    volume_size: 15
  tasks:
    - name: Fail if availability zones are different
      ansible.builtin.fail:
        msg: AZs are different
      when: "hostvars[source]['placement']['availability_zone'] != hostvars[dest]['placement']['availability_zone']"

    - name: Share AWS region
      ansible.builtin.set_fact:
        aws_region: "{{ hostvars[source]['placement']['region'] }}"

    - name: Attach new volume to source
      amazon.aws.ec2_vol:
        device_name: "{{ hostvars[source]['block_device_mappings'][0]['device_name'] + 'tmp' }}"
        instance: "{{ hostvars[source]['instance_id'] }}"
        region: "{{ aws_region }}"
        state: present
        volume_size: "{{ volume_size }}"
        volume_type: gp2
