---
- name: Prepare volume
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Get device name
      ansible.builtin.set_fact:
          new_volume_device_name: >-
            {{
            (
              ['f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
              | map('regex_replace', '(.)', '/dev/sd\1')
              | list
              | difference(
                  hostvars[dest].block_device_mappings
                    | map(attribute='device_name')
                    | list
                )
              )[0]
            }}

    - ansible.builtin.debug:
        msg: "Next device: {{ new_volume_device_name }}"

    - name: Attach new volume to source
      amazon.aws.ec2_vol:
        device_name: "{{ new_volume_device_name }}"
        instance: "{{ hostvars[source]['instance_id'] }}"
        region: "{{ hostvars[source]['placement']['region'] }}"
        state: present
        volume_size: "{{ volume_size }}"
        volume_type: gp2
        tags:
          Name: temp_volume
      register: volume_for_backups

    - name: Debug volume
      ansible.builtin.debug:
        var: volume_for_backups

- name: Create backups
  gather_facts: false
  hosts: "{{ az_group }}:&{{ source }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    source: "{{ source | default('skip') }}"
  tasks:
    - name: Build connection details
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details
      delegate_to: localhost

    - name: Reboot to add a new disk
      ansible.windows.win_reboot:

    - name: Add Disk
      ansible.builtin.include_role:
        name: prepare_disk

    - name: Create Migration-script folder
      ansible.windows.win_file:
        path: C:\Migration-script
        state: directory

    - name: Create Migration folder
      ansible.windows.win_file:
        path: C:\Migration
        state: directory

    - name: Create Migration folder
      ansible.windows.win_file:
        path: D:\Backups
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Backup-Databases.ps1.j2
        dest: C:\Migration-script\Backup-Databases.ps1
        force: true

    - name: Execute SQL backup script
      ansible.windows.win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File C:\Migration-script\Backup-Databases.ps1
      args:
        executable: powershell.exe


- name: Restore backups
  gather_facts: false
  hosts: "{{ az_group }}:&{{ dest }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    source: "{{ dest | default('skip') }}"
  tasks:

    - name: Build connection details
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details
      delegate_to: localhost

    - name: Detach volume from the source
      amazon.aws.ec2_vol:
        id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
        instance: "None"
        region: "{{ hostvars[dest]['placement']['region'] }}"
        modify_volume: true
      delegate_to: localhost

    - name: Wait for volume to be available
      amazon.aws.ec2_vol_info:
        filters:
          - volume-id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
          - status: "available"
      register: result

    - name: Debug result
      ansible.builtin.debug:
        var: result
      # until: result | length > 0
      # retries: 5
      # delay: 10
    - name: Wait for volume to be available 2
      amazon.aws.ec2_vol_info:
        filters:
          volume-id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
          status: "available"
      register: result2

    - name: Debug result
      ansible.builtin.debug:
        var: result2

    - name: Attach new volume to source
      amazon.aws.ec2_vol:
        id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
        device_name: "{{ hostvars['localhost']['new_volume_device_name'] }}"
        instance: "{{ hostvars[dest]['instance_id'] }}"
        region: "{{ hostvars[dest]['placement']['region'] }}"
        state: present
      register: attachment_result

    - name: Reboot to add a new disk
      ansible.windows.win_reboot:
