---
# - name: Prepare volume
#   gather_facts: false
#   hosts: localhost
#   tasks:
#     - name: Set databases names
#       ansible.builtin.set_fact:
#         AN_Database: "AlloyNavigatorExpress"
#         AD_Database: "AlloyNavigatorExpress.ad"
#         AN_RegistryName: "Alloy Navigator Express"
#         AN_ProductName: "Alloy Navigator Express"
#       when: ProductIsExpress

#     - name: Get device name
#       ansible.builtin.set_fact:
#           new_volume_device_name: >-
#             {{
#             (
#               ['f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
#               | map('regex_replace', '(.)', '/dev/sd\1')
#               | list
#               | difference(
#                   hostvars[dest].block_device_mappings
#                     | map(attribute='device_name')
#                     | list
#                 )
#               )[0]
#             }}

#     - ansible.builtin.debug:
#         msg: "Next device: {{ new_volume_device_name }}"

#     - name: Attach new volume to source
#       amazon.aws.ec2_vol:
#         device_name: "{{ new_volume_device_name }}"
#         instance: "{{ hostvars[source]['instance_id'] }}"
#         region: "{{ hostvars[source]['placement']['region'] }}"
#         state: present
#         volume_size: "{{ volume_size }}"
#         volume_type: gp2
#         tags:
#           Name: temp_volume
#       register: volume_for_backups

#     - name: Debug volume
#       ansible.builtin.debug:
#         var: volume_for_backups

# - name: Create backups
#   gather_facts: false
#   hosts: "{{ az_group }}:&{{ source }}"
#   vars:
#     az_group: "{{ availability_zone_group | default('skip') }}"
#     source: "{{ source | default('skip') }}"
#     is_initialized: false

#   tasks:
#     - name: Build connection details
#       block:
#         - name: Build connection details
#           ansible.builtin.include_role:
#             name: build_connection_details
#       delegate_to: localhost
#       no_log: true

#     - name: Try creating a backup and Cleanup
#       block:

#         - name: Add Disk
#           ansible.builtin.include_role:
#             name: prepare_disk

#         - name: Set backup path
#           ansible.builtin.set_fact:
#             source_mssql_backup_path: "{{ next_drive_letter }}{{ mssql_backup_path }}"

#         - name: Create Migration folder
#           ansible.windows.win_file:
#             path: "{{ source_mssql_backup_path }}"
#             state: directory

#         - name: Create database backups on Windows
#           community.general.mssql_script:
#             login_host: "{{ hostvars[source]['ansible_host'] }}"
#             login_user: "{{ source_SaUserName }}"
#             login_password: "{{ source_SaPassword }}"
#             login_port: 51967
#             name: master
#             script: |
#               ALTER DATABASE [{{ item }}] SET ONLINE;
#               ALTER DATABASE [{{ item }}]
#               SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

#               DECLARE @BackupPath NVARCHAR(500) = N'{{ source_mssql_backup_path }}\{{ item }}.bak'

#               BACKUP DATABASE [{{ item }}]
#               TO DISK = @BackupPath
#               WITH FORMAT,
#                     MEDIANAME = '{{ item }}_Backup',
#                     NAME = 'Full Backup of {{ item }}';

#               PRINT 'Backup created successfully: ' + @BackupPath

#               ALTER DATABASE [{{ item }}] SET OFFLINE;
#           loop: "{{ database_list }}"
#           delegate_to: localhost
#           register: backup_result

#         - name: Show backup results
#           ansible.builtin.debug:
#             var: backup_result.results

#       rescue:
#         - name: Delete volume.
#           amazon.aws.ec2_vol:
#             id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
#           # id: "{{ volume_id }}"
#             region: "{{ hostvars[dest]['placement']['region'] }}"
#             modify_volume: true
#             state: absent
#           delegate_to: localhost

# - name: Restore backups
#   gather_facts: false
#   hosts: "{{ az_group }}:&{{ dest }}"
#   vars:
#     az_group: "{{ availability_zone_group | default('skip') }}"
#     dest: "{{ dest | default('skip') }}"

#     volume_id: vol-01dde0a878cd44fb6
#     is_initialized: true


#   tasks:
#     - name: Build connection details
#       block:
#         - name: Build connection details
#           ansible.builtin.include_role:
#             name: build_connection_details

#         - name: Detach volume from the source
#           amazon.aws.ec2_vol:
#             id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
#             # id: "{{ volume_id }}"
#             instance: "None"
#             region: "{{ hostvars[dest]['placement']['region'] }}"
#             modify_volume: true

#         - name: Wait for volume to be available
#           amazon.aws.ec2_vol_info:
#             filters:
#               # volume-id: "{{ volume_id }}"
#               volume-id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
#               status: "available"
#             region: "{{ hostvars[dest]['placement']['region'] }}"
#           register: result
#           until: result | length > 0
#           retries: 5
#           delay: 10

#         - name: Attach new volume to dest
#           amazon.aws.ec2_vol:
#             id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
#             # id: "{{ volume_id }}"
#             device_name: "{{ hostvars['localhost']['new_volume_device_name'] }}"
#             # device_name: /dev/sdg
#             instance: "{{ hostvars[dest]['instance_id'] }}"
#             region: "{{ hostvars[dest]['placement']['region'] }}"
#             state: present
#           register: attachment_result
#       delegate_to: localhost

#     - name: Add Disk 2
#       ansible.builtin.include_role:
#         name: prepare_disk

#     - name: Set backup path
#       ansible.builtin.set_fact:
#         target_mssql_backup_path: "{{ current_drive }}{{ mssql_backup_path }}"

#     - name: Ensure backup file
#       ansible.windows.win_stat:
#         path: "{{ target_mssql_backup_path }}\\{{ item }}.bak"
#       loop: "{{ database_list }}"
#       register: files

#     - name: Debug files
#       ansible.builtin.debug:
#         var: files

#     - name: Create database backups on Windows
#       community.general.mssql_script:
#         login_host: "{{ hostvars[dest]['ansible_host'] }}"
#         login_user: "{{ dest_SaUserName }}"
#         login_password: "{{ dest_SaPassword }}"
#         login_port: 51967
#         name: master
#         script: |

#           RESTORE DATABASE [{{ prefix }}-{{ item }}]
#           FROM DISK = '{{ target_mssql_backup_path }}\{{ item }}.bak'
#           WITH
#               MOVE '{{ item }}'     TO '{{ target_mssql_backup_path }}\{{ prefix }}-{{ item }}.mdf',
#               MOVE '{{ item }}_log' TO '{{ target_mssql_backup_path }}\{{ prefix }}-{{ item }}_log.ldf',
#               REPLACE,
#               STATS = 5;
#           ALTER DATABASE [{{ prefix }}-{{ item }}] SET ONLINE;
#           ALTER DATABASE [{{ prefix }}-{{ item }}] SET MULTI_USER WITH ROLLBACK IMMEDIATE;
#       loop: "{{ database_list }}"
#       delegate_to: localhost
#       register: backup_result

- name: Reconfigure source
  gather_facts: false
  hosts: "{{ az_group }}:&{{ source }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    source: "{{ source | default('skip') }}"
    sql_s3_bucket: "alloy-software-installers"
    sql_s3_object: "ScriptHelper.exe"
    sql_s3_url_expiry: 3600
    sql_s3_region_effective: "{{ hostvars[source]['placement']['region'] }}"
  tasks:
    - name: Build connection details
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details
      delegate_to: localhost

    - name: Generate installer presigned URL
      delegate_to: localhost
      amazon.aws.s3_object:
        mode: geturl
        bucket: "{{ sql_s3_bucket }}"
        object: "{{ sql_s3_object }}"
        expiry: "{{ sql_s3_url_expiry }}"
        region: "{{ sql_s3_region_effective }}"
      register: helper_url

    - name: Share url
      delegate_to: localhost
      ansible.builtin.set_fact:
        helper_url: "{{ helper_url.url }}"

    - name: Download script "ScriptHelper.exe"
      ansible.windows.win_get_url:
        url: "{{ helper_url }}"
        dest: C:\Install

    - name: Ensure script folder
      ansible.builtin.win_file:
        path: C:\Migration-script
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Reconfigure-Source.ps1.j2
        dest: C:\Migration-script\Reconfigure-Source.ps1
        force: true

    - name: Execute SQL restore script
      ansible.windows.win_shell: |
        & C:\Migration-script\Reconfigure-Source.ps1
      args:
        executable: powershell.exe
