---
- name: Prepare volume
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Set databases names
      ansible.builtin.set_fact:
        AN_Database: "AlloyNavigatorExpress"
        AD_Database: "AlloyNavigatorExpress.ad"
        AN_RegistryName: "Alloy Navigator Express"
        AN_ProductName: "Alloy Navigator Express"
      when: ProductIsExpress

    - name: Get device name
      ansible.builtin.set_fact:
          new_volume_device_name: >-
            {{
            (
              ['f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
              | map('regex_replace', '(.)', '/dev/sd\1')
              | list
              | difference(
                  hostvars[dest].block_device_mappings
                    | map(attribute='device_name')
                    | list
                )
              )[0]
            }}

    - ansible.builtin.debug:
        msg: "Next device: {{ new_volume_device_name }}"

    - name: Attach new volume to source
      amazon.aws.ec2_vol:
        device_name: "{{ new_volume_device_name }}"
        instance: "{{ hostvars[source]['instance_id'] }}"
        region: "{{ hostvars[source]['placement']['region'] }}"
        state: present
        volume_size: "{{ volume_size }}"
        volume_type: gp2
        tags:
          Name: temp_volume
      register: volume_for_backups

    - name: Debug volume
      ansible.builtin.debug:
        var: volume_for_backups

- name: Create backups
  gather_facts: false
  hosts: "{{ az_group }}:&{{ source }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    source: "{{ source | default('skip') }}"
    mssql_backup_path: D:\Backups
    database_list:
      - "{{ AN_Database }}"
      # - "{{ AD_Database }}"
  tasks:
    - name: Build connection details
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details
      delegate_to: localhost
      no_log: true

    # - name: Reboot to add a new disk
    #   ansible.windows.win_reboot:
    #     reboot_timeout: 300
    #   register: reboot_result

    # - name: Cleanup on reboot hang
    #   block:
    #     - name: Delete volume.
    #       amazon.aws.ec2_vol:
    #         id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
    #       # id: "{{ volume_id }}"
    #         region: "{{ hostvars[dest]['placement']['region'] }}"
    #         modify_volume: true
    #         state: absent
    #       delegate_to: localhost

    #     - name: Fail
    #       ansible.builtin.fail:
    #         msg: Failed as requested from task
    #   when: not reboot_result.rebooted


    - name: Try creating a backup and Cleanup
      block:
        - name: Add Disk
          ansible.builtin.include_role:
            name: prepare_disk

        - name: Create Migration folder
          ansible.windows.win_file:
            path: "{{ mssql_backup_path }}"
            state: directory

        - name: Create database backups on Windows
          community.general.mssql_script:
            login_host: "{{ ansible_host }}"
            login_user: "{{ source_SaUserName }}"
            login_password: "{{ source_SaPassword }}"
            login_port: 51967
            name: "{{ item }}"
            script: |
              DECLARE @BackupPath NVARCHAR(500) = N'{{ mssql_backup_path }}\{{ item }}.bak'

              BACKUP DATABASE [{{ item }}]
              TO DISK = @BackupPath
              WITH COMPRESSION, FORMAT,
                    MEDIANAME = '{{ item }}_Backup',
                    NAME = 'Full Backup of {{ item }}';

              PRINT 'Backup created successfully: ' + @BackupPath
          loop: "{{ database_list }}"
          register: backup_result

        - name: Show backup results
          ansible.builtin.debug:
            var: backup_result.results

      rescue:
        - name: Delete volume.
          amazon.aws.ec2_vol:
            id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
          # id: "{{ volume_id }}"
            region: "{{ hostvars[dest]['placement']['region'] }}"
            modify_volume: true
            state: absent
          delegate_to: localhost


#     - name: Create Migration-script folder
#       ansible.windows.win_file:
#         path: C:\Migration-script
#         state: directory

#     - name: Create Migration folder
#       ansible.windows.win_file:
#         path: C:\Migration
#         state: directory

#

#     - name: Generate script
#       ansible.windows.win_template:
#         src: templates/Backup-Databases.ps1.j2
#         dest: C:\Migration-script\Backup-Databases.ps1
#         force: true

#     - name: Execute SQL backup script
#       ansible.windows.win_shell: |
#         & C:\Migration-script\Backup-Databases.ps1
#       args:
#         executable: powershell.exe


#     - name: Detach volume from the source
#       amazon.aws.ec2_vol:
#         id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
#         # id: "{{ volume_id }}"
#         instance: "None"
#         region: "{{ hostvars[dest]['placement']['region'] }}"
#         modify_volume: true
#       delegate_to: localhost

#     - name: Wait for volume to be available
#       amazon.aws.ec2_vol_info:
#         filters:
#           # volume-id: "{{ volume_id }}"
#           volume-id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
#           status: "available"
#         region: "{{ hostvars[dest]['placement']['region'] }}"
#       register: result
#       delegate_to: localhost
#       until: result | length > 0
#       retries: 5
#       delay: 10





# - name: Restore backups
#   gather_facts: false
#   hosts: "{{ az_group }}:&{{ dest }}"
#   vars:
#     az_group: "{{ availability_zone_group | default('skip') }}"
#     dest: "{{ dest | default('skip') }}"
#     prefix: migrated
#     volume_id: vol-006d4057fac43208b

#   tasks:
#     - name: Build connection details
#       block:
#         - name: Build connection details
#           ansible.builtin.include_role:
#             name: build_connection_details
#       delegate_to: localhost



#     - name: Attach new volume to dest
#       amazon.aws.ec2_vol:
#         id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
#         # id: "{{ volume_id }}"
#         device_name: "{{ hostvars['localhost']['new_volume_device_name'] }}"
#         # device_name: /dev/sdg
#         instance: "{{ hostvars[dest]['instance_id'] }}"
#         region: "{{ hostvars[dest]['placement']['region'] }}"
#         state: present
#       register: attachment_result
#       delegate_to: localhost

#     - name: Reboot to add a new disk
#       ansible.windows.win_reboot:

#     # - name: Gather disk facts
#     #   community.windows.win_disk_facts:

#     # - name: Select last disk (the newly attached one)
#     #   ansible.builtin.set_fact:
#     #     last_disk: "{{ ansible_facts.disks | sort(attribute='number') | last }}"
#     #     last_disk_number: "{{ ansible_facts.disks | map(attribute='number') | max }}"

#     # - name: Get used drive letters
#     #   ansible.builtin.set_fact:
#     #     used_letters: >-
#     #       {{ ansible_facts.disks
#     #         | map(attribute='volumes')
#     #         | flatten
#     #         | selectattr('drive_letter', 'defined')
#     #         | map(attribute='drive_letter')
#     #         | map('upper')
#     #         | list }}

#     # - name: Determine first available drive letter
#     #   ansible.builtin.set_fact:
#     #     available_drive_letter: >-
#     #       {{ (range(67, 91)
#     #           | map('chr')
#     #           | difference(used_letters)
#     #           | list)[0] }}

#     # - name: Assign drive letter to the last disks first partition
#     #   community.windows.win_partition:
#     #     disk_number: "{{ last_disk_number }}"
#     #     partition_number: 1
#     #     drive_letter: "{{ available_drive_letter }}"
#     #   when:
#     #     - last_disk.partitions | length > 0
#     #     - last_disk.partitions[0].drive_letter is not defined

#     - name: Create Migration-script folder
#       ansible.windows.win_file:
#         path: C:\Migration-script
#         state: directory

#     - name: Generate script
#       ansible.windows.win_template:
#         src: templates/Restore-Databases.ps1.j2
#         dest: C:\Migration-script\Restore-Databases.ps1
#         force: true

#     - name: Execute SQL restore script
#       ansible.windows.win_shell: |
#         & C:\Migration-script\Restore-Databases.ps1
#       args:
#         executable: powershell.exe

# - name: Reconfigure source
#   gather_facts: false
#   hosts: "{{ az_group }}:&{{ source }}"
#   vars:
#     az_group: "{{ availability_zone_group | default('skip') }}"
#     source: "{{ source | default('skip') }}"
#     sql_s3_bucket: "alloy-software-installers"
#     sql_s3_object: "ScriptHelper.exe"
#     sql_s3_url_expiry: 3600
#     sql_s3_region_effective: hostvars[source]['placement']['region']
#   tasks:

#     - name: Generate installer presigned URL
#       delegate_to: localhost
#       amazon.aws.s3_object:
#         mode: geturl
#         bucket: "{{ sql_s3_bucket }}"
#         object: "{{ sql_s3_object }}"
#         expiry: "{{ sql_s3_url_expiry }}"
#         region: "{{ sql_s3_region_effective }}"
#       register: helper_url

#     - name: Share url
#       delegate_to: localhost
#       ansible.builtin.set_fact:
#         helper_url: "{{ helper_url.url }}"

#     - name: Download script "ScriptHelper.exe"
#       ansible.windows.win_get_url:
#         url: "{{ helper_url }}"
#         dest: C:\Install

#     - name: Generate script
#       ansible.windows.win_template:
#         src: templates/Reconfigure-Source.ps1.j2
#         dest: C:\Migration-script\Reconfigure-Source.ps1
#         force: true

#     - name: Execute SQL restore script
#       ansible.windows.win_shell: |
#         & C:\Migration-script\Reconfigure-Source.ps1
#       args:
#         executable: powershell.exe

#     - name: Reboot source
#       ansible.windows.win_reboot:

