---
- name: Create backups
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Set databases names when express
      ansible.builtin.set_fact:
        AN_Database: "AlloyNavigatorExpress"
        AD_Database: "AlloyNavigatorExpress.ad"
        AN_RegistryName: "Alloy Navigator Express"
        AN_ProductName: "Alloy Navigator Express"
      when: ProductIsExpress

    - name: Set databases names when not express
      ansible.builtin.set_fact:
        AN_RegistryName: "Alloy Navigator"
        AN_ProductName: "Alloy Navigator"
        AN_Database: "AlloyNavigator"
        AD_Database: "AlloyDiscovery"
      when: not ProductIsExpress

    - name: Set database list
      ansible.builtin.set_fact:
        database_list:
          - "{{ AN_Database }}"
          - "{{ AD_Database }}"

    - name: Initialize passwords
      ansible.builtin.set_fact:
        passwords: {}

    - name: Generate unique passwords for each database
      ansible.builtin.set_fact:
        passwords: "{{ passwords | combine({ item: lookup('password', '/dev/null', chars='ascii_letters,digits,hexdigits', length=20) }) }}"
      loop: "{{ database_list }}"

    - name: Get device name
      ansible.builtin.set_fact:
          new_volume_device_name: >-
            {{
            (
              ['f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
              | map('regex_replace', '(.)', '/dev/sd\1')
              | list
              | difference(
                  hostvars[dest].block_device_mappings
                    | map(attribute='device_name')
                    | list
                )
              )[0]
            }}

    - ansible.builtin.debug:
        msg: "Next device: {{ new_volume_device_name }}"

    - name: Attach new volume to source
      amazon.aws.ec2_vol:
        device_name: "{{ new_volume_device_name }}"
        instance: "{{ hostvars[source]['instance_id'] }}"
        region: "{{ hostvars[source]['placement']['region'] }}"
        state: present
        volume_size: "{{ volume_size }}"
        volume_type: gp2
        resource_tags:
          Name: "{{ prefix }}-temp_volume"
      register: volume_for_backups

    - name: Debug volume
      ansible.builtin.debug:
        var: volume_for_backups

- name: Prepare disk
  gather_facts: false
  hosts: "{{ az_group }}:&{{ source }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    source: "{{ source | default('skip') }}"
    is_initialized: false
  tasks:
    - name: Build connection details
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details
      delegate_to: localhost
      no_log: true

    - name: Add Disk
      ansible.builtin.include_role:
        name: prepare_disk

    - name: Set backup path
      ansible.builtin.set_fact:
        source_mssql_backup_path: "{{ next_drive_letter }}{{ mssql_backup_path }}"

    - name: Create Migration folder
      ansible.windows.win_file:
        path: "{{ source_mssql_backup_path }}"
        state: directory

- name: Create backups
  hosts: localhost
  vars:
    source_mssql_backup_path: "{{ hostvars[source]['source_mssql_backup_path'] }}"
    database_list: "{{ hostvars['localhost']['database_list'] }}"
  tasks:

    - name: Create database backups on Windows
      community.general.mssql_script:
        login_host: "{{ hostvars[source]['ansible_host'] }}"
        login_user: "{{ source_SaUserName }}"
        login_password: "{{ source_SaPassword }}"
        login_port: 51967
        name: master
        script: |
          ALTER DATABASE [{{ item }}] SET ONLINE;
          ALTER DATABASE [{{ item }}]
          SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

          DECLARE @BackupPath NVARCHAR(500) = N'{{ source_mssql_backup_path }}\{{ item }}.bak'

          BACKUP DATABASE [{{ item }}]
          TO DISK = @BackupPath
          WITH FORMAT,
                MEDIANAME = '{{ item }}_Backup',
                NAME = 'Full Backup of {{ item }}';

          PRINT 'Backup created successfully: ' + @BackupPath

          ALTER DATABASE [{{ item }}] SET OFFLINE;
      loop: "{{ database_list }}"
      delegate_to: localhost
      register: backup_result

    - name: Show backup results
      ansible.builtin.debug:
        var: backup_result.results

- name: Re-attach volume to "{{ dest }}"
  hosts: localhost
  tasks:
    - name: Detach volume from the source
      amazon.aws.ec2_vol:
        id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
        # id: "{{ volume_id }}"
        instance: "None"
        region: "{{ hostvars[dest]['placement']['region'] }}"
        modify_volume: true

    - name: Wait for volume to be available
      amazon.aws.ec2_vol_info:
        filters:
          # volume-id: "{{ volume_id }}"
          volume-id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
          status: "available"
        region: "{{ hostvars[dest]['placement']['region'] }}"
      register: result
      until: result | length > 0
      retries: 5
      delay: 10

    - name: Attach new volume to dest
      amazon.aws.ec2_vol:
        id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
        # id: "{{ volume_id }}"
        device_name: "{{ hostvars['localhost']['new_volume_device_name'] }}"
        # device_name: /dev/sdg
        instance: "{{ hostvars[dest]['instance_id'] }}"
        region: "{{ hostvars[dest]['placement']['region'] }}"

    - name: Wait for volume to be in-use
      amazon.aws.ec2_vol_info:
        filters:
          # volume-id: "{{ volume_id }}"
          volume-id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
          status: "in-use"
        region: "{{ hostvars[dest]['placement']['region'] }}"
      register: result
      until: result | length > 0
      retries: 5
      delay: 10

- name: Prepare media
  gather_facts: false
  hosts: "{{ az_group }}:&{{ dest }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    dest: "{{ dest | default('skip') }}"
    is_initialized: true
    database_list: "{{ hostvars['localhost']['database_list'] }}"
  tasks:
    - name: Build connection details
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details
      delegate_to: localhost
      no_log: true

    - name: Reboot host
      ansible.windows.win_reboot:
        post_reboot_delay: 60

    - name: Add Disk 2
      ansible.builtin.include_role:
        name: prepare_disk

    - name: Set backup path
      ansible.builtin.set_fact:
        target_mssql_backup_path: "{{ current_drive }}{{ mssql_backup_path }}"

    - name: Ensure backup file
      ansible.windows.win_stat:
        path: "{{ target_mssql_backup_path }}\\{{ item }}.bak"
      loop: "{{ database_list }}"
      register: files

    - name: Fail if any backup file is missing
      ansible.builtin.fail:
        msg: "Backup file for one or more databases is missing!"
      when: >
        files.results | selectattr('stat.exists', 'equalto', false) | list | length > 0


- name: Restore databases and create users
  hosts: localhost
  vars:
    target_mssql_backup_path: "{{ hostvars[dest]['target_mssql_backup_path'] }}"
    database_list: "{{ hostvars['localhost']['database_list'] }}"
  tasks:
    - name: Restore databases
      community.general.mssql_script:
        login_host: "{{ hostvars[dest]['ansible_host'] }}"
        login_user: "{{ dest_SaUserName }}"
        login_password: "{{ dest_SaPassword }}"
        login_port: 51967
        name: master
        script: |
          RESTORE DATABASE [{{ prefix }}-{{ item }}]
          FROM DISK = '{{ target_mssql_backup_path }}\{{ item }}.bak'
          WITH
              MOVE '{{ item }}'     TO '{{ target_mssql_backup_path }}\{{ prefix }}-{{ item }}.mdf',
              MOVE '{{ item }}_log' TO '{{ target_mssql_backup_path }}\{{ prefix }}-{{ item }}_log.ldf',
              REPLACE,
              STATS = 5;
          ALTER DATABASE [{{ prefix }}-{{ item }}] SET ONLINE;
          ALTER DATABASE [{{ prefix }}-{{ item }}] SET MULTI_USER WITH ROLLBACK IMMEDIATE;

          IF NOT EXISTS (select 1 from sys.sql_logins where name = '{{ prefix }}-dbreader')
            CREATE LOGIN [{{ prefix }}-dbreader] WITH PASSWORD = '{{ db_reader_password }}', CHECK_POLICY = OFF;
            GRANT CONNECT SQL TO [{{ prefix }}-dbreader];

          CREATE LOGIN [{{ prefix }}-{{ item }}Access] WITH PASSWORD = '{{ hostvars['localhost']['passwords'][item] }}', CHECK_POLICY = OFF;
          GRANT CONNECT SQL TO [{{ prefix }}-{{ item }}Access];
          GRANT VIEW ANY DEFINITION TO [{{ prefix }}-{{ item }}Access];
          GRANT VIEW SERVER STATE TO [{{ prefix }}-{{ item }}Access];
      loop: "{{ database_list }}"
      no_log: false
      register: backup_result

    - name: Create users
      community.general.mssql_script:
        login_host: "{{ hostvars[dest]['ansible_host'] }}"
        login_user: "{{ dest_SaUserName }}"
        login_password: "{{ dest_SaPassword }}"
        login_port: 51967
        name: "{{ prefix }}-{{ item }}"
        script: |
          IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'{{ prefix }}-{{ item }}Access')
            CREATE USER [{{ prefix }}-{{ item }}Access] FOR LOGIN [{{ prefix }}-{{ item }}Access];
          IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'{{ prefix }}-dbreader')
            CREATE USER [{{ prefix }}-dbreader] FOR LOGIN [{{ prefix }}-dbreader];
          ALTER ROLE [db_owner] ADD MEMBER [{{ prefix }}-{{ item }}Access];
          ALTER ROLE [db_datareader] ADD MEMBER [{{ prefix }}-dbreader];
          DENY INSERT, UPDATE, DELETE  TO [{{ prefix }}-dbreader];
      loop: "{{ database_list }}"
      register: backup_result

- name: Reconfigure source
  gather_facts: false
  hosts: "{{ az_group }}:&{{ source }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    source: "{{ source | default('skip') }}"
    sql_s3_bucket: "alloy-software-installers"
    sql_s3_object: "ScriptHelper.exe"
    sql_s3_url_expiry: 3600
    sql_s3_region_effective: "{{ hostvars[source]['placement']['region'] }}"
    passwords: "{{ hostvars['localhost']['passwords'] }}"
  tasks:
    - name: Debug localhost
      ansible.builtin.debug:
        var: hostvars['localhost']

    - name: Generate installer presigned URL
      delegate_to: localhost
      amazon.aws.s3_object:
        mode: geturl
        bucket: "{{ sql_s3_bucket }}"
        object: "{{ sql_s3_object }}"
        expiry: "{{ sql_s3_url_expiry }}"
        region: "{{ sql_s3_region_effective }}"
      register: helper_url

    - name: Share url
      ansible.builtin.set_fact:
        helper_url: "{{ helper_url.url }}"

    - name: Download script "ScriptHelper.exe"
      ansible.windows.win_get_url:
        url: "{{ helper_url }}"
        dest: C:\Install

    - name: Ensure script folder
      ansible.builtin.win_file:
        path: C:\Migration-script
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Reconfigure-Source.ps1.j2
        dest: C:\Migration-script\Reconfigure-Source.ps1
        force: true

    - name: Execute SQL restore script
      ansible.windows.win_shell: |
        & C:\Migration-script\Reconfigure-Source.ps1
      args:
        executable: powershell.exe

    - name: Restart IIS
      ansible.windows.win_service:
        name: W3SVC
        state: restarted
