---
- name: Prepare ebs_vol
  gather_facts: false
  hosts: localhost
  vars:
    prefix: "{{ source.split('.')[0] }}"
  tasks:
    - name: Set databases names when express
      ansible.builtin.set_fact:
        AN_RegistryName: "Alloy Navigator Express"
        AN_ProductName: "Alloy Navigator Express"
      when: ProductIsExpress

    - name: Set databases names when not express
      ansible.builtin.set_fact:
        AN_RegistryName: "Alloy Navigator"
        AN_ProductName: "Alloy Navigator"
      when: not ProductIsExpress

    - name: Get non system databases
      community.general.mssql_script:
        login_host: "{{ hostvars[source]['ansible_host'] }}"
        login_user: "{{ source_SaUserName }}"
        login_password: "{{ source_SaPassword }}"
        login_port: 51967
        name: master
        script: |
          SELECT name
          FROM sys.databases
          WHERE name NOT IN ('master', 'model', 'msdb', 'tempdb')
          ORDER BY name;
      register: query_result

    - name: Extract database names into a simple list
      ansible.builtin.set_fact:
        database_list: "{{ query_result.query_results[0][0] | map('first') | list }}"

    - name: Show database list
      ansible.builtin.debug:
        var: database_list

    - name: Attach new volume to source
      amazon.aws.ec2_vol:
        device_name: "/dev/xvdf"
        instance: "{{ hostvars[source]['instance_id'] }}"
        region: "{{ hostvars[source]['placement']['region'] }}"
        state: present
        volume_size: "{{ volume_size }}"
        volume_type: gp3
        resource_tags:
          Name: "{{ prefix }}-migration_volume"
      register: volume_for_backups

    - name: Set stats for later
      ansible.builtin.set_stats:
        data:
          volume_id: "{{ volume_for_backups['volume']['id'] }}"
          AN_RegistryName: "{{ AN_RegistryName }}"
          AN_ProductName: "{{ AN_ProductName }}"

- name: Prepare disk and backup registry
  gather_facts: false
  hosts: "{{ source }}"
  vars:
    is_initialized: false
    source: "{{ source | default('skip') }}"
    mssql_backup_path: :\Backups
    reg_file_path: :\Regfiles
    downloads_path: :\Downloads
    AN_RegistryName: "{{ hostvars['localhost']['AN_RegistryName'] }}"
    site_name: "{{ site_name | default('Default Web Site') }}"
  tasks:
    - name: Add Disk
      ansible.builtin.include_role:
        name: prepare_disk

    - name: Set backup path
      ansible.builtin.set_fact:
        source_mssql_backup_path: "{{ next_drive_letter }}{{ mssql_backup_path }}"
        source_reg_file_path: "{{ next_drive_letter }}{{ reg_file_path }}"
        source_downloads_path: "{{ next_drive_letter }}{{ downloads_path }}"

    - name: Create Migration folder
      ansible.windows.win_file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ source_mssql_backup_path }}"
        - "{{ source_reg_file_path }}"


    - name: Export Registry Keys
      ansible.windows.win_shell: |
        $outputDir = "{{ source_reg_file_path }}"
        reg export "HKCU\Software\Alloy Software\{{ AN_RegistryName }}\Connections" `
            "$outputDir\user_connection.reg" /y
        reg export "HKLM\SOFTWARE\Alloy Software\{{ AN_RegistryName }}\Service Connection" `
            "$outputDir\an_service_connection.reg" /y
        {% if not ProductIsExpress %}
        reg export "HKLM\SOFTWARE\Alloy Software\Alloy Discovery\Service Connection" `
            "$outputDir\ad_service_connection.reg" /y
        {% endif %}
        $AccessKeysRootPath = "HKLM:\SOFTWARE\Alloy Software\Access Keys"
        $subKeys = Get-ChildItem -Path $AccessKeysRootPath
        foreach ($key in $subKeys) {
            $keyName = Split-Path $key.PSPath -Leaf
            $fileName = (($keyName -split ':') | % {$_.trim() })[1]
            $outputFile = Join-Path $outputDir "$fileName.reg"
            reg export $key.Name.Replace('HKEY_LOCAL_MACHINE', 'HKLM') $outputFile /y
          }

    - name: Export {{ site_name }} bindings to JSON
      ansible.windows.win_shell: |
        Import-Module WebAdministration

        $siteName = '{{ site_name }}'

        $bindings = Get-WebBinding -Name $siteName | ForEach-Object {
            [PSCustomObject]@{
                protocol = $_.protocol
                bindingInformation = $_.bindingInformation
            }
        }

        $bindings | ConvertTo-Json -Depth 3 -Compress
      register: default_site_bindings

    - name: Copy folder only if destination is missing
      ansible.windows.win_shell: |
        $src = 'C:\ProgramData\Alloy Software\Downloads'
        $dst = '{{ source_downloads_path }}'

        if (-not (Test-Path $dst)) {
            Copy-Item -Path $src -Destination $dst -Recurse -Force
            Write-Output "CHANGED"
        }

    - name: Set stats for later
      ansible.builtin.set_stats:
        data:
          database_list: "{{ hostvars['localhost']['database_list'] }}"
          region: "{{ hostvars[source]['placement']['region'] }}"
          mssql_backup_path: "{{ hostvars[source]['source_mssql_backup_path'] }}"
          default_site_bindings: "{{ default_site_bindings.stdout }}"

- name: Create backups
  hosts: localhost
  vars:
    region: "{{ hostvars[dest]['placement']['region'] }}"
    volume_id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
    mssql_backup_path: "{{ hostvars[source]['source_mssql_backup_path'] }}"
  tasks:

    - name: Create database backups on Windows
      community.general.mssql_script:
        login_host: "{{ hostvars[source]['ansible_host'] }}"
        login_user: "{{ source_SaUserName }}"
        login_password: "{{ source_SaPassword }}"
        login_port: 51967
        name: master
        script: |
          ALTER DATABASE [{{ item }}] SET ONLINE;
          ALTER DATABASE [{{ item }}]
          SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

          DECLARE @BackupPath NVARCHAR(500) = N'{{ mssql_backup_path }}\{{ item }}.bak'

          BACKUP DATABASE [{{ item }}]
          TO DISK = @BackupPath
          WITH FORMAT,
                MEDIANAME = '{{ item }}_Backup',
                NAME = 'Full Backup of {{ item }}';

          PRINT 'Backup created successfully: ' + @BackupPath

          ALTER DATABASE [{{ item }}] SET OFFLINE;
      loop: "{{ database_list }}"
      register: backup_result

    - name: Show backup results
      ansible.builtin.debug:
        var: backup_result.results

    - name: Detach volume from the source
      amazon.aws.ec2_vol:
        id: "{{ volume_id}}"
        instance: "None"
        region: "{{ region }}"
        modify_volume: true

    - name: Wait for volume to be available
      amazon.aws.ec2_vol_info:
        filters:
          volume-id: "{{ volume_id}}"
          status: "available"
        region: "{{ region }}"
      register: result
      until: result | length > 0
      retries: 5
      delay: 10

    - name: Attach new volume to dest
      amazon.aws.ec2_vol:
        id: "{{ volume_id}}"
        device_name: "/dev/xvdf"
        instance: "{{ hostvars[dest]['instance_id'] }}"
        region: "{{ region }}"

    - name: Wait for volume to be in-use
      amazon.aws.ec2_vol_info:
        filters:
          volume-id: "{{ volume_id}}"
          status: "in-use"
        region: "{{ region }}"
      register: result
      until: result | length > 0
      retries: 5
      delay: 10
