---
- name: Prepare ebs_vol
  gather_facts: false
  hosts: localhost
  vars:
    prefix: "{{ source.split('.')[0] }}"
  tasks:
    - name: Set databases names when express
      ansible.builtin.set_fact:
        AN_Database: "AlloyNavigatorExpress"
        AD_Database: "AlloyNavigatorExpress.ad"
        AN_RegistryName: "Alloy Navigator Express"
        AN_ProductName: "Alloy Navigator Express"
      when: ProductIsExpress

    - name: Set databases names when not express
      ansible.builtin.set_fact:
        AN_RegistryName: "Alloy Navigator"
        AN_ProductName: "Alloy Navigator"
        AN_Database: "AlloyNavigator"
        AD_Database: "AlloyDiscovery"
      when: not ProductIsExpress

    - name: Set database list
      ansible.builtin.set_fact:
        database_list:
          - "{{ AN_Database }}"
          - "{{ AD_Database }}"

    - name: Set stats for later
      ansible.builtin.set_stats:
        data:
          an_db: "{{ AN_Database }}"
          ad_db: "{{ AD_Database }}"
          an_rn: "{{ AN_RegistryName }}"
          an_pn: "{{ AN_ProductName }}"

    - name: Initialize passwords
      ansible.builtin.set_fact:
        passwords: {}

    - name: Generate unique passwords for each database
      ansible.builtin.set_fact:
        passwords: "{{ passwords | combine({ item: lookup('password', '/dev/null', chars='ascii_letters,digits,hexdigits', length=20) }) }}"
      loop: "{{ database_list }}"

    - name: Get device name
      ansible.builtin.set_fact:
          new_volume_device_name: >-
            {{
            (
              ['f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
              | map('regex_replace', '(.)', '/dev/sd\1')
              | list
              | difference(
                  hostvars[dest].block_device_mappings
                    | map(attribute='device_name')
                    | list
                )
              )[0]
            }}

    - ansible.builtin.debug:
        msg: "Next device: {{ new_volume_device_name }}"

    - name: Attach new volume to source
      amazon.aws.ec2_vol:
        device_name: "{{ new_volume_device_name }}"
        instance: "{{ hostvars[source]['instance_id'] }}"
        region: "{{ hostvars[source]['placement']['region'] }}"
        state: present
        volume_size: "{{ volume_size }}"
        volume_type: gp2
        resource_tags:
          Name: "{{ prefix }}-migration_volume"
      register: volume_for_backups

    - name: Debug volume
      ansible.builtin.debug:
        var: volume_for_backups

- name: Prepare disk
  gather_facts: false
  hosts: "{{ source }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    source: "{{ source | default('skip') }}"
    is_initialized: false
  tasks:
    - name: Build connection details
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details
      delegate_to: localhost
      no_log: true

    - name: Add Disk
      ansible.builtin.include_role:
        name: prepare_disk

    - name: Set backup path
      ansible.builtin.set_fact:
        source_mssql_backup_path: "{{ next_drive_letter }}{{ mssql_backup_path }}"

    - name: Create Migration folder
      ansible.windows.win_file:
        path: "{{ source_mssql_backup_path }}"
        state: directory

- name: Create backups
  hosts: localhost
  vars:
    source_mssql_backup_path: "{{ hostvars[source]['source_mssql_backup_path'] }}"
    database_list: "{{ hostvars['localhost']['database_list'] }}"
  tasks:
    - name: Create database backups on Windows
      community.general.mssql_script:
        login_host: "{{ hostvars[source]['ansible_host'] }}"
        login_user: "{{ source_SaUserName }}"
        login_password: "{{ source_SaPassword }}"
        login_port: 51967
        name: master
        script: |
          ALTER DATABASE [{{ item }}] SET ONLINE;
          ALTER DATABASE [{{ item }}]
          SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

          DECLARE @BackupPath NVARCHAR(500) = N'{{ source_mssql_backup_path }}\{{ item }}.bak'

          BACKUP DATABASE [{{ item }}]
          TO DISK = @BackupPath
          WITH FORMAT,
                MEDIANAME = '{{ item }}_Backup',
                NAME = 'Full Backup of {{ item }}';

          PRINT 'Backup created successfully: ' + @BackupPath

          ALTER DATABASE [{{ item }}] SET OFFLINE;
      loop: "{{ database_list }}"
      register: backup_result

    - name: Show backup results
      ansible.builtin.debug:
        var: backup_result.results

- name: Re-attach volume to "{{ dest }}"
  hosts: localhost
  tasks:
    - name: Detach volume from the source
      amazon.aws.ec2_vol:
        id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
        instance: "None"
        region: "{{ hostvars[dest]['placement']['region'] }}"
        modify_volume: true

    - name: Wait for volume to be available
      amazon.aws.ec2_vol_info:
        filters:
          volume-id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
          status: "available"
        region: "{{ hostvars[dest]['placement']['region'] }}"
      register: result
      until: result | length > 0
      retries: 5
      delay: 10

    - name: Attach new volume to dest
      amazon.aws.ec2_vol:
        id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
        device_name: "{{ hostvars['localhost']['new_volume_device_name'] }}"
        instance: "{{ hostvars[dest]['instance_id'] }}"
        region: "{{ hostvars[dest]['placement']['region'] }}"

    - name: Wait for volume to be in-use
      amazon.aws.ec2_vol_info:
        filters:
          volume-id: "{{ hostvars['localhost']['volume_for_backups']['volume']['id'] }}"
          status: "in-use"
        region: "{{ hostvars[dest]['placement']['region'] }}"
      register: result
      until: result | length > 0
      retries: 5
      delay: 10

- name: Prepare media
  gather_facts: false
  hosts: "{{ dest }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    dest: "{{ dest | default('skip') }}"
    is_initialized: true
    database_list: "{{ hostvars['localhost']['database_list'] }}"
  tasks:
    - name: Build connection details
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details
      delegate_to: localhost
      no_log: true

    # - name: Reboot host
    #   ansible.windows.win_reboot:
    #     post_reboot_delay: 180

    - name: Add Disk 2
      ansible.builtin.include_role:
        name: prepare_disk

    - name: Set backup path
      ansible.builtin.set_fact:
        target_mssql_backup_path: "{{ current_drive }}{{ mssql_backup_path }}"

    - name: Ensure backup file
      ansible.windows.win_stat:
        path: "{{ target_mssql_backup_path }}\\{{ item }}.bak"
      loop: "{{ database_list }}"
      register: files

    - name: Fail if any backup file is missing
      ansible.builtin.fail:
        msg: "Backup file for one or more databases is missing!"
      when: >
        files.results | selectattr('stat.exists', 'equalto', false) | list | length > 0

    - name: Set stats for later
      ansible.builtin.set_stats:
        data:
          target_mssql_backup_path: "{{ hostvars[dest]['target_mssql_backup_path'] }}"
          database_list: "{{ hostvars['localhost']['database_list'] }}"
          passwords: "{{ hostvars['localhost']['passwords'] }}"
