---
- name: Restore databases and create users
  hosts: localhost
  vars:
    backup_path: "{{ target_mssql_backup_path | default('no_path') }}"
    db_list: "{{ database_list | default([])}}"
    prefix: "{{ source.split('.')[0] }}"
  tasks:
    - name: Debug
      ansible.builtin.debug:
        var: prefix

    # - name: Check if prefix already exists
    #   community.general.mssql_script:
    #     login_host: "{{ hostvars[source]['ansible_host'] }}"
    #     login_user: "{{ source_SaUserName }}"
    #     login_password: "{{ source_SaPassword }}"
    #     login_port: 51967
    #     name: master
    #     script: |
    #       select count(*) as [Value] from sys.databases where name like '{{ prefix }}%'
    #   register: databases_count

    # - name: Debug count
    #   ansible.builtin.debug:
    #     var: databases_count

    # - name: Fail when prefix not uninque
    #   ansible.builtin.fail:
    #   when: (databases_count['query_results'][0][0][0][0] | default(1)) > 0

    # - name: Debug connection vars
    #   ansible.builtin.debug:
    #     var: dest_SaPassword

    - name: Delete existing databases
      community.general.mssql_script:
        login_host: "{{ hostvars[dest]['ansible_host'] }}"
        login_user: "{{ dest_SaUserName }}"
        login_password: "{{ dest_SaPassword }}"
        login_port: 51967
        name: master
        script: |
          DROP DATABASE [{{ item }}]
      loop: "{{ database_list }}"
      no_log: false
      register: restoration_result

    - name: Restore databases
      community.general.mssql_script:
        login_host: "{{ hostvars[dest]['ansible_host'] }}"
        login_user: "{{ dest_SaUserName }}"
        login_password: "{{ dest_SaPassword }}"
        login_port: 51967
        name: master
        script: |
          RESTORE DATABASE [{{ item }}]
          FROM DISK = '{{ target_mssql_backup_path }}\{{ item }}.bak'
          --WITH
          --    MOVE '{{ item }}'     TO '{{ target_mssql_backup_path }}\{{ item }}.mdf',
          --    MOVE '{{ item }}_log' TO '{{ target_mssql_backup_path }}\{{ item }}_log.ldf',
          --    REPLACE,
          --    STATS = 5;
          ALTER DATABASE [{{ item }}] SET ONLINE;
          ALTER DATABASE [{{ item }}] SET MULTI_USER WITH ROLLBACK IMMEDIATE;

          IF NOT EXISTS (select 1 from sys.sql_logins where name = 'dbreader')
            CREATE LOGIN [dbreader] WITH PASSWORD = '{{ db_reader_password }}', CHECK_POLICY = OFF;
            GRANT CONNECT SQL TO [dbreader];

          IF NOT EXISTS (select 1 from sys.sql_logins where name = 'dbreader')
            CREATE LOGIN [{{ item }}Access] WITH PASSWORD = '{{ hostvars['localhost']['passwords'][item] }}', CHECK_POLICY = OFF;
          GRANT CONNECT SQL TO [{{ item }}Access];
          GRANT VIEW ANY DEFINITION TO [{{ item }}Access];
          GRANT VIEW SERVER STATE TO [{{ item }}Access];
      loop: "{{ database_list }}"
      no_log: false
      register: restoration_result

    - name: Create users
      community.general.mssql_script:
        login_host: "{{ hostvars[dest]['ansible_host'] }}"
        login_user: "{{ dest_SaUserName }}"
        login_password: "{{ dest_SaPassword }}"
        login_port: 51967
        name: "{{ item }}"
        script: |
          IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'{{ item }}Access')
            CREATE USER [{{ item }}Access] FOR LOGIN [{{ item }}Access];
          IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = N'dbreader')
            CREATE USER [dbreader] FOR LOGIN [dbreader];
          ALTER ROLE [db_owner] ADD MEMBER [{{ item }}Access];
          ALTER ROLE [db_datareader] ADD MEMBER [dbreader];
          DENY INSERT, UPDATE, DELETE  TO [dbreader];
      loop: "{{ database_list }}"
      register: user_creation_result

- name: Reconfigure AWS side
  gather_facts: false
  hosts: localhost
  vars:
    domain_name: "{{ source }}"
    zone_id: "{{ hosted_zone_id }}"
  tasks:
    - name: Get Route 53 record details
      amazon.aws.route53_info:
        type: A
        hosted_zone_id: "{{ zone_id }}"
        query: record_sets
        start_record_name: "{{ domain_name }}"
      register: route53_info

    - name: Extract IP address from record
      ansible.builtin.set_fact:
        record_ip: "{{ route53_info.resource_record_sets[0].resource_records[0].value }}"

    - name: Get EIP allocation ID by IP address
      amazon.aws.ec2_eip_info:
        region: "{{ hostvars[source]['placement']['region'] }}"
        filters:
          "public-ip": "{{ record_ip }}"
      register: eip_info

    - name: Debug EIP info
      ansible.builtin.debug:
        var: eip_info

    - name: Debug Allocation ID info
      ansible.builtin.debug:
        msg: "Allocation ID: {{ eip_info.addresses[0].allocation_id }}"

    - name: Release current association
      amazon.aws.ec2_eip:
        device_id: "{{ hostvars[source]['instance_id'] }}"
        ip: "{{ record_ip }}"
        state: absent
      register: release_result

    - name: Associate to new instance
      amazon.aws.ec2_eip:
        device_id: "{{ hostvars[dest]['instance_id'] }}"
        ip: "{{ record_ip }}"
        state: present
      register: association_result

    - name: Verify association
      amazon.aws.ec2_eip_info:
        region: "{{ hostvars[source]['placement']['region'] }}"
        filters:
          "public-ip": "{{ record_ip }}"
      register: verification
      until: verification.addresses[0].instance_id == hostvars[dest]['instance_id']
      retries: 5
      delay: 5

    - name: Delete volume
      amazon.aws.ec2_vol:
        id: "{{ volume_id }}"
        state: absent

- name: Configure destination
  gather_facts: false
  hosts: "{{ dest }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    source: "{{ source | default('skip') }}"
    sql_s3_bucket: "alloy-software-installers"
    sql_s3_object: "ScriptHelper.exe"
    sql_s3_url_expiry: 3600
    prefix: "{{ source.split('.')[0] }}"
    passwords: "{{ passwords | default({}) }}"
  tasks:
    - name: Build connection details
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details
      delegate_to: localhost
      no_log: true

    - name: Get and update hostname in bindings
      microsoft.iis.website_info:


























    - name: Get Script Helper URL
      delegate_to: localhost
      amazon.aws.s3_object:
        mode: geturl
        bucket: "{{ sql_s3_bucket }}"
        object: "{{ sql_s3_object }}"
        expiry: "{{ sql_s3_url_expiry }}"
        region: "{{ sql_s3_region_effective }}"
      register: helper_url

    - name: Download script "ScriptHelper.exe"
      ansible.windows.win_get_url:
        url: "{{ helper_url.url }}"
        dest: C:\Install

    - name: Ensure script folder
      ansible.builtin.win_file:
        path: C:\Migration-script
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Reconfigure-Source.ps1.j2
        dest: C:\Migration-script\Reconfigure-Source.ps1
        force: true

    - name: Execute SQL restore script
      ansible.windows.win_shell: |
        & C:\Migration-script\Reconfigure-Source.ps1
      args:
        executable: powershell.exe

    - name: Restart IIS
      ansible.windows.win_service:
        name: W3SVC
        state: restarted
