---
- name: Prepare media
  gather_facts: false
  hosts: "{{ source }}"
  vars:
    source: "{{ source | default('skip') }}"
    is_initialized: true
    sql_s3_object: "ScriptHelper.exe"
    sql_s3_url_expiry: 3600
  tasks:
    # - name: Add Disk To Destination
    #   ansible.builtin.include_role:
    #     name: prepare_disk

    - name: Bring disk online
      ansible.windows.win_shell: |
        $disk = Get-Disk -Number 1
        if ($disk.OperationalStatus -eq 'Offline') {
            Set-Disk -Number 1 -IsOffline $false
            Write-Host "Disk 1 is now online" -ForegroundColor Green
        } else {
            Write-Host "Disk 1 is already online" -ForegroundColor Yellow
        }
      args:
        executable: powershell.exe

    - name: Set backup path
      ansible.builtin.set_fact:
        target_mssql_backup_path: "D{{ mssql_backup_path }}"

    - name: Ensure backup file
      ansible.windows.win_stat:
        path: "{{ target_mssql_backup_path }}\\{{ item }}.bak"
      loop: "{{ database_list }}"
      register: files

    - name: Fail if any backup file is missing
      ansible.builtin.fail:
        msg: "Backup file for one or more databases is missing!"
      when: >
        files.results | selectattr('stat.exists', 'equalto', false) | list | length > 0

    - name: Remove all bindings from Default Web Site
      ansible.windows.win_shell: |
        Import-Module WebAdministration

        $siteName = 'Default Web Site'

        Get-WebBinding -Name $siteName | ForEach-Object {
            Remove-WebBinding `
                -Name $siteName `
                -Protocol $_.protocol `
                -BindingInformation $_.bindingInformation
        }

    - name: Restore Default Web Site bindings from exported JSON
      ansible.windows.win_shell: |
        Import-Module WebAdministration

        $siteName = 'Default Web Site'

        $json = @'
        {{ default_site_bindings }}
        '@

        $bindings = $json | ConvertFrom-Json

        foreach ($b in $bindings) {
            if (-not (Get-WebBinding -Name $siteName -Protocol $b.protocol `
                      | Where-Object { $_.bindingInformation -eq $b.bindingInformation })) {

                New-WebBinding `
                    -Name $siteName `
                    -Protocol $b.protocol `
                    -BindingInformation $b.bindingInformation
            }
        }


    - name: Ensure script folder
      ansible.builtin.win_file:
        path: C:\Remove-Old-Renewals-Install-New-Certs
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Remove-Old-Renewals-Install-New-Certs.ps1.j2
        dest: C:\Remove-Old-Renewals-Install-New-Certs\Remove-Old-Renewals-Install-New-Certs.ps1
        force: true

    - name: Execute renewals script
      ansible.windows.win_shell: |
        & C:\Remove-Old-Renewals-Install-New-Certs\Remove-Old-Renewals-Install-New-Certs.ps1
      args:
        executable: powershell.exe

    - name: Get Script Helper URL
      delegate_to: localhost
      amazon.aws.s3_object:
        mode: geturl
        bucket: "{{ sql_s3_bucket }}"
        object: "{{ sql_s3_object }}"
        expiry: "{{ sql_s3_url_expiry }}"
        region: "{{ hostvars[source]['placement']['region'] }}"
      register: helper_url

    - name: Download script "ScriptHelper.exe"
      ansible.windows.win_get_url:
        url: "{{ helper_url.url }}"
        dest: C:\Install

    - name: Ensure script folder
      ansible.builtin.win_file:
        path: C:\Migration-script
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Reconfigure-Source.ps1.j2
        dest: C:\Migration-script\Reconfigure-Source.ps1
        force: true

    - name: Execute SQL restore script
      ansible.windows.win_shell: |
        & C:\Migration-script\Reconfigure-Source.ps1
      args:
        executable: powershell.exe

    - name: Change computer name
      ansible.windows.win_hostname:
        name: "{{ computer_name }}"

    - name: Reboot destination
      ansible.windows.win_reboot:

- name: Reconfigure AWS side
  gather_facts: false
  hosts: localhost
  vars:
    region: "{{ hostvars[dest]['placement']['region'] }}"
  tasks:
    - name: Delete volume
      amazon.aws.ec2_vol:
        id: "{{ volume_id }}"
        state: absent
        region: "{{ region }}"
