---
- name: Restore databases
  gather_facts: false
  hosts: "{{ dest }}"
  vars:
    dest: "{{ dest | default('skip') }}"
    is_initialized: true
    sql_s3_object: "ScriptHelper.exe"
    sql_s3_url_expiry: 3600
    new_hostname: "{{
        (
          default_site_bindings
          | from_json
          | selectattr('bindingInformation', 'search', domain_name)
          | map(attribute='bindingInformation')
          | map('regex_replace', '^.*:', '')
          | first
        )
      }}"

  tasks:
    - name: Add Disk To Destination
      ansible.builtin.include_role:
        name: prepare_disk

    - name: Bring disk online
      ansible.windows.win_shell: |
        $disk = Get-Disk -Number 1
        if ($disk.OperationalStatus -eq 'Offline') {
            Set-Disk -Number 1 -IsOffline $false
            Write-Host "Disk 1 is now online" -ForegroundColor Green
        } else {
            Write-Host "Disk 1 is already online" -ForegroundColor Yellow
        }
      args:
        executable: powershell.exe

    - name: Set backup path
      ansible.builtin.set_fact:
        target_mssql_backup_path: "{{ mssql_backup_path }}"

    - name: Ensure backup file
      ansible.windows.win_stat:
        path: "{{ target_mssql_backup_path }}\\{{ item }}.bak"
      loop: "{{ database_list }}"
      register: files

    - name: Fail if any backup file is missing
      ansible.builtin.fail:
        msg: "Backup file for one or more databases is missing!"
      when: >
        files.results | selectattr('stat.exists', 'equalto', false) | list | length > 0

    - name: Add new hostname to hosts
      community.windows.win_lineinfile:
        path: C:\Windows\System32\drivers\etc\hosts
        line: "127.0.0.1 {{ new_hostname }}"

    - name: Remove all subkeys under Alloy Software Access Keys
      ansible.windows.win_shell: |
        $baseKey = 'HKLM:\SOFTWARE\Alloy Software\Access Keys'
        if (Test-Path $baseKey) {
            Get-ChildItem -Path $baseKey | ForEach-Object {
                Remove-Item -Path $_.PsPath -Recurse -Force
            }
        }

    - name: Remove all subkeys from Alloy Navigator Connections (HKCU)
      ansible.windows.win_shell: |
        $baseKey = 'HKCU:\Software\Alloy Software\{{ AN_RegistryName }}\Connections'

        if (Test-Path $baseKey) {
            Get-ChildItem $baseKey | ForEach-Object {
                Remove-Item $_.PsPath -Recurse -Force
            }
        }

    - name: Remove all subkeys from Alloy Discovery Connections (HKCU)
      ansible.windows.win_shell: |
        $baseKey = 'HKCU:\Software\Alloy Software\Alloy Discovery\Connections'

        if (Test-Path $baseKey) {
            Get-ChildItem $baseKey | ForEach-Object {
                Remove-Item $_.PsPath -Recurse -Force
            }
        }
      when: not ProductIsExpress

    - name: Remove all bindings from Default Web Site
      ansible.windows.win_shell: |
        Import-Module WebAdministration

        $siteName = 'Default Web Site'

        Get-WebBinding -Name $siteName | ForEach-Object {
            Remove-WebBinding `
                -Name $siteName `
                -Protocol $_.protocol `
                -BindingInformation $_.bindingInformation
        }

    - name: Restore Default Web Site bindings from exported JSON
      ansible.windows.win_shell: |

        Import-Module WebAdministration

        $siteName = 'Default Web Site'

        $json = @'
        {{ default_site_bindings }}
        '@

        $bindings = $json | ConvertFrom-Json

        foreach ($b in $bindings) {

            # Split "*:port:host"
            $parts = $b.bindingInformation -split ':', 3
            $ip   = $parts[0]
            $port = [int]$parts[1]
            $hostname = $parts[2]

            $exists = Get-WebBinding -Name $siteName -Protocol $b.protocol |
                Where-Object {
                    $_.bindingInformation -eq $b.bindingInformation
                }
            if (-not $exists) {
                New-WebBinding `
                    -Name $siteName `
                    -Protocol $b.protocol `
                    -Port $port `
                    -IPAddress $ip `
                    -HostHeader $hostname
          }
        }


    # - name: Get Script Helper URL
    #   delegate_to: localhost
    #   amazon.aws.s3_object:
    #     mode: geturl
    #     bucket: "{{ sql_s3_bucket }}"
    #     object: "{{ sql_s3_object }}"
    #     expiry: "{{ sql_s3_url_expiry }}"
    #     region: "{{ hostvars[dest]['placement']['region'] }}"
    #   register: helper_url

    # - name: Download script "ScriptHelper.exe"
    #   ansible.windows.win_get_url:
    #     url: "{{ helper_url.url }}"
    #     dest: C:\Install

    - name: Download helper locally
      delegate_to: localhost
      amazon.aws.s3_object:
        bucket: "{{ sql_s3_bucket }}"
        object: "{{ sql_s3_object }}"
        dest: /tmp/ScriptHelper.exe
        mode: get

    - name: Copy helper to Windows
      ansible.windows.win_copy:
        src: /tmp/ScriptHelper.exe
        dest: C:\Install\ScriptHelper.exe

    - name: Ensure script folder
      ansible.builtin.win_file:
        path: C:\Migration-script
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Reconfigure-Source.ps1.j2
        dest: C:\Migration-script\Reconfigure-Source.ps1
        force: true

    - name: Execute SQL restore script
      ansible.windows.win_shell: |
        & C:\Migration-script\Reconfigure-Source.ps1
      args:
        executable: powershell.exe

    - name: Mirror D:\Downloads to ProgramData Alloy Downloads
      ansible.windows.win_shell: >
        robocopy "D:\Downloads" "C:\ProgramData\Alloy Software\Downloads"
        /MIR /R:1 /W:1 /NFL /NDL
      register: robocopy_result
      ignore_errors: true

- name: Reconfigure AWS side
  gather_facts: false
  hosts: localhost
  vars:
    region: "{{ hostvars[dest]['placement']['region'] }}"
  tasks:

    - name: Stop source
      amazon.aws.ec2_instance:
        instance_ids:
          - "{{ hostvars[source]['instance_id'] }}"
        region: "{{ hostvars[source]['placement']['region'] }}"
        state: stopped
        wait: true

    - name: Delete volume
      amazon.aws.ec2_vol:
        id: "{{ volume_id }}"
        state: absent
        region: "{{ region }}"

    - name: Delete restored volume
      amazon.aws.ec2_vol:
        id: "{{ restored_volume_id }}"
        state: absent
        region: "{{ region }}"
      when: restored_volume_id is defined

    - name: Extract IP address from record
      ansible.builtin.set_fact:
        record_ip: "{{ hostvars[source]['ansible_host'] }}"

    - name: Get EIP allocation ID by IP address
      amazon.aws.ec2_eip_info:
        region: "{{ region }}"
        filters:
          "public-ip": "{{ record_ip }}"
      register: eip_info

    - name: Release current association
      amazon.aws.ec2_eip:
        region: "{{ region }}"
        device_id: "{{ hostvars[source]['instance_id'] }}"
        ip: "{{ record_ip }}"
        state: absent
      register: release_result

    - name: Associate to new instance
      amazon.aws.ec2_eip:
        region: "{{ region }}"
        device_id: "{{ hostvars[dest]['instance_id'] }}"
        ip: "{{ record_ip }}"
        state: present
      register: association_result

    - name: Verify association
      amazon.aws.ec2_eip_info:
        region: "{{ region }}"
        filters:
          "public-ip": "{{ record_ip }}"
      register: verification
      until: verification.addresses[0].instance_id == hostvars[dest]['instance_id']
      retries: 5
      delay: 5
