---
- name: Generate key
  hosts: aws_ec2
  gather_facts: false
  vars:
    provision_private_key_path_expanded: "~/{{ inventory_hostname }}.pem"
    provision_public_key_path_expanded: "~/{{ inventory_hostname }}.pub"
  tasks:
    - name: Generate keys
      delegate_to: localhost
      connection: local
      remote_user: root
      block:
        - name: Check home directory
          ansible.builtin.command: pwd
          register: pwd_result
          changed_when: false

        - name: Check home directory
          ansible.builtin.command: echo $HOME
          register: home_result
          changed_when: false

        - name: Display writable directories
          ansible.builtin.debug:
            msg:
              - "Current directory: {{ pwd_result.stdout }}"
              - "Home directory: {{ home_result.stdout }}"

    #     - name: Ensure SSH key directory exists
    #       ansible.builtin.file:
    #         path: "{{ provision_private_key_path_expanded | dirname }}"
    #         state: directory
    #         mode: '0700'

    #     - name: Generate key pair
    #       ansible.builtin.shell: |
    #         umask 0177
    #         ssh-keygen -t {{ ec2_ssh_key_type }} \
    #           -b {{ ec2_ssh_key_bits }} \
    #           -m PEM \
    #           -f "{{ provision_private_key_path_expanded }}" \
    #           -N "" \
    #           -C "ansible-generated-{{ ec2_key_name }}"
    #       changed_when: false

    #     - name: Read public key content
    #       ansible.builtin.slurp:
    #         src: "{{ provision_public_key_path_expanded }}"
    #       register: public_key_content

    #     - name: Read private key content for Vault storage
    #       ansible.builtin.slurp:
    #         src: "{{ provision_private_key_path_expanded }}"
    #       register: private_key_content

    #     - name: Show private key
    #       ansible.builtin.debug:
    #         var: private_key_content

    # - name: Write to the authorized keys
    #   community.windows.win_lineinfile:
    #     state: present
    #     insertafter: EOF
    #     path: C:\ProgramData\ssh\administrators_authorized_keys
    #     line: "{{ public_key_content }}"

    # - name: Build Vault payload for SSH secret
    #   ansible.builtin.set_fact:
    #     provision_vault_payload:
    #       private_key: "{{ private_key_content }}"

    # - name: Store SSH secret
    #   delegate_to: localhost
    #   block:
    #     - name: Manage secret
    #       ansible.builtin.include_role:
    #         name: manage_secret
    #       vars:
    #         manage_secret_action: write
    #         manage_secret_payload: "{{ provision_vault_payload }}"
    #         manage_secret_path: "windows/{{ inventory_hostname }}"
    #       register: provision_ec2_vault_write_result

    #     - name: Debug write result
    #       ansible.builtin.debug:
    #         var: provision_ec2_vault_write_result
    #       when: "provision_ec2_vault_write_result is defined"

    #     - name: Verify stored SSH secret
    #       ansible.builtin.include_role:
    #         name: manage_secret
    #       vars:
    #         manage_secret_action: get
    #         manage_secret_path: "windows/{{ inventory_hostname }}"
