---
- name: Generate key
  hosts: aws_ec2
  gather_facts: false
  vars:
    ec2_ssh_key_type: rsa
    ec2_ssh_key_bits: 4096
  tasks:
    - name: Remove chroot for all users
      community.windows.win_lineinfile:
        path: C:\ProgramData\ssh\sshd_config
        line: ChrootDirectory "C:\inetpub\ftproot\Audits"
        state: absent

    - name: Add chroot for FTP user
      community.windows.win_lineinfile:
        path: C:\ProgramData\ssh\sshd_config
        state: present
        create: false
        insertafter: EOF
        line: |
          Match User FTPUser
              ChrootDirectory  "C:\inetpub\ftproot\Audits"

    - name: Restart SSH service
      ansible.windows.win_service:
        name: sshd
        state: restarted
