---
- name: Generate key
  hosts: aws_ec2
  gather_facts: false
  vars:
    ec2_ssh_key_type: rsa
    ec2_ssh_key_bits: 4096
  tasks:
    - name: Generate keys
      delegate_to: localhost
      connection: local
      remote_user: root
      block:
        - name: Derive private key file paths
          ansible.builtin.set_fact:
            provision_private_key_path: "{{ lookup('env', 'HOME') }}/.ssh/{{ inventory_hostname }}.pem"

        - name: Derive public key file paths
          ansible.builtin.set_fact:
            provision_public_key_path: "{{ provision_private_key_path }}.pub"

        - name: Ensure SSH key directory exists
          ansible.builtin.file:
            path: "{{ provision_private_key_path | dirname }}"
            state: directory
            mode: '0700'

        - name: Generate key pair
          ansible.builtin.shell: |
            umask 0177
            ssh-keygen -t {{ ec2_ssh_key_type }} \
              -b {{ ec2_ssh_key_bits }} \
              -m PEM \
              -f "{{ provision_private_key_path }}" \
              -N "" \
              -C "ansible-generated-{{ inventory_hostname }}"
          changed_when: false

        - name: Read public key content
          ansible.builtin.slurp:
            src: "{{ provision_public_key_path }}"
          register: public_key_content
          delegate_facts: false

        - name: Read private key content for Vault storage
          ansible.builtin.slurp:
            src: "{{ provision_private_key_path }}"
          register: private_key_content

        - name: Share private key
          ansible.builtin.set_fact:
            private_key: "{{ private_key_content.content | b64decode }}"

        - name: Share public key
          ansible.builtin.set_fact:
            public_key: "{{ public_key_content.content | b64decode }}"

    - name: Remove chroot for all users
      community.windows.win_lineinfile:
        path: C:\ProgramData\ssh\sshd_config
        line: ChrootDirectory "C:\inetpub\ftproot\Audits"
        state: absent

    - name: Add chroot for FTP user
      community.windows.win_lineinfile:
        path: C:\ProgramData\ssh\sshd_config
        state: present
        create: false
        insertafter: EOF
        line: |
          Match User FTPUser
              ChrootDirectory  "C:\inetpub\ftproot\Audits"

    - name: Restart SSH service
      ansible.windows.win_service:
        name: sshd
        state: restarted

    - name: Ensure script folder
      ansible.windows.win_file:
        path: C:\Install-AdminKeyScript
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Install-AdminKey.ps1.j2
        dest: C:\Install-AdminKeyScript\Reconfigure-Source.ps1
        force: true

    - name: Execute key install script
      ansible.windows.win_shell: |
        & C:\Install-AdminKeyScript\Reconfigure-Source.ps1
      args:
        executable: powershell.exe

    - name: Build Vault payload for SSH secret
      ansible.builtin.set_fact:
        provision_vault_payload:
          private_key: "{{ private_key }}"

    - name: Store SSH secret
      delegate_to: localhost
      block:
        - name: Manage secret
          ansible.builtin.include_role:
            name: manage_secret
          vars:
            manage_secret_action: write
            manage_secret_payload: "{{ provision_vault_payload }}"
            manage_secret_path: "windows/{{ hostvars[inventory_hostname]['instance_id'] }}"
          register: provision_ec2_vault_write_result

        - name: Debug write result
          ansible.builtin.debug:
            var: provision_ec2_vault_write_result
          when: "provision_ec2_vault_write_result is defined"

        - name: Verify stored SSH secret
          ansible.builtin.include_role:
            name: manage_secret
          vars:
            manage_secret_action: get
            manage_secret_path: "windows/{{ hostvars[inventory_hostname]['instance_id'] }}"
