---
- name: Configure destination
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Delete volume
      amazon.aws.ec2_vol:
        id: "{{ volume_id }}"
        state: absent
        region: "{{ region }}"

- name: Reboot hosts
  gather_facts: false
  hosts: "{{ source }}, {{ dest }}"
  vars:
    dest: "{{ dest | default('skip') }}"
    source: "{{ source | default('skip') }}"
  tasks:
    - name: Reboot hosts
      ansible.windows.win_reboot:
