---
- name: Configure destination
  gather_facts: false
  hosts: localhost
  tasks:
    # - name: Restore multiuser
    #   community.general.mssql_script:
    #     login_host: "{{ hostvars[source]['ansible_host'] }}"
    #     login_user: "{{ source_SaUserName }}"
    #     login_password: "{{ source_SaPassword }}"
    #     login_port: 51967
    #     name: master
    #     script: |
    #       ALTER DATABASE [{{ item }}] SET ONLINE;
    #       ALTER DATABASE [{{ item }}]
    #       SET MULTI_USER WITH ROLLBACK IMMEDIATE;

    #   loop: "{{ database_list }}"
    #   register: backup_result

    - name: Delete volume
      amazon.aws.ec2_vol:
        id: "{{ volume_id }}"
        state: absent
        region: "{{ hostvars[source].placement.region }}"

    - name: Delete restored volume
      amazon.aws.ec2_vol:
        id: "{{ restored_volume_id }}"
        state: absent
        region: "{{ hostvars[dest].placement.region }}"
      when: restored_volume_id is defined

- name: Reboot hosts
  gather_facts: false
  hosts: "{{ source }}, {{ dest }}"
  vars:
    dest: "{{ dest | default('skip') }}"
    source: "{{ source | default('skip') }}"
  tasks:
    - name: Reboot hosts
      ansible.windows.win_reboot:

- name: Fail
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Set status failed
      ansible.builtin.fail:
        msg: Something went wrong during the migration. Please review the log above
