- name: Configure destination
  gather_facts: false
  hosts: "{{ source }}"
  vars:
    az_group: "{{ availability_zone_group | default('skip') }}"
    source: "{{ source | default('skip') }}"
    sql_s3_bucket: "alloy-software-installers"
    sql_s3_object: "ScriptHelper.exe"
    sql_s3_url_expiry: 3600
    prefix: "{{ source.split('.')[0] }}"
    passwords: "{{ passwords | default({}) }}"
  tasks:
    - name: Build connection details
      block:
        - name: Build connection details
          ansible.builtin.include_role:
            name: build_connection_details
      delegate_to: localhost
      no_log: true

    - name: Get and update hostname in bindings
      microsoft.iis.website_info:
        name: Default Web Site
      register: website_info

    - name: Delete existing bindings
      microsoft.iis.website:
        name: Default Web Site
        bindings:
          set:

    - name: Add new bindings
      microsoft.iis.website:
        name: Default Web Site
        bindings:
          add:
            - ip: '*'
              hostname: "{{ source }}"
              port: 80
            - ip: '*'
              hostname: "{{ source }}"
              port: 443

    - name: Ensure script folder
      ansible.builtin.win_file:
        path: C:\Remove-Old-Renewals-Install-New-Certs
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Remove-Old-Renewals-Install-New-Certs.ps1.j2
        dest: C:\Remove-Old-Renewals-Install-New-Certs\Remove-Old-Renewals-Install-New-Certs.ps1
        force: true

    - name: Execute SQL restore script
      ansible.windows.win_shell: |
        & C:\Remove-Old-Renewals-Install-New-Certs\Remove-Old-Renewals-Install-New-Certs.ps1
      args:
        executable: powershell.exe

    - name: Get Script Helper URL
      delegate_to: localhost
      amazon.aws.s3_object:
        mode: geturl
        bucket: "{{ sql_s3_bucket }}"
        object: "{{ sql_s3_object }}"
        expiry: "{{ sql_s3_url_expiry }}"
        region: "{{ sql_s3_region_effective }}"
      register: helper_url

    - name: Download script "ScriptHelper.exe"
      ansible.windows.win_get_url:
        url: "{{ helper_url.url }}"
        dest: C:\Install

    - name: Ensure script folder
      ansible.builtin.win_file:
        path: C:\Migration-script
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Reconfigure-Source.ps1.j2
        dest: C:\Migration-script\Reconfigure-Source.ps1
        force: true

    - name: Execute SQL restore script
      ansible.windows.win_shell: |
        & C:\Migration-script\Reconfigure-Source.ps1
      args:
        executable: powershell.exe

    - name: Restart IIS
      ansible.windows.win_service:
        name: W3SVC
        state: restarted
