---
- name: Check connection
  hosts: aws_ec2
  gather_facts: false
  tasks:
    - name: Try win_stat something
      ansible.windows.win_shell: |
        Get-Date
      register: result

    - name: Show result
      ansible.builtin.debug:
        var: result
