- name: Issue new certs
  gather_facts: false
  hosts: "{{ dest }}"
  vars:
    dest: "{{ dest | default('skip') }}"
  tasks:
    - name: Ensure script folder
      ansible.builtin.win_file:
        path: C:\Remove-Old-Renewals-Install-New-Certs
        state: directory

    - name: Generate script
      ansible.windows.win_template:
        src: templates/Remove-Old-Renewals-Install-New-Certs.ps1.j2
        dest: C:\Remove-Old-Renewals-Install-New-Certs\Remove-Old-Renewals-Install-New-Certs.ps1
        force: true

    - name: Execute renewals script
      ansible.windows.win_shell: |
        & C:\Remove-Old-Renewals-Install-New-Certs\Remove-Old-Renewals-Install-New-Certs.ps1
      args:
        executable: powershell.exe
