---
- name: Debug Route53 access from AWX
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:

    - name: Show AWS caller identity (VERY IMPORTANT)
      amazon.aws.aws_caller_info:
      register: caller

    - name: Debug caller identity
      ansible.builtin.debug:
        var: caller

    - name: List hosted zones
      amazon.aws.route53_info:
        query: hosted_zone
        hosted_zone_method: details
      register: zones

    - name: Debug hosted zones
      ansible.builtin.debug:
        var: zones
