---
- name: List D drive contents
  gather_facts: false
  hosts: aws_ec2
  tasks:
    - name: List all drives
      ansible.windows.win_powershell:
        script: Get-PSDrive -PSProvider FileSystem | Format-Table Name, Used, Free, Provider, Root -AutoSize
      register: drives

    - name: Show drives
      ansible.builtin.debug:
        var: drives.stdout_lines

    - name: Get D drive contents
      ansible.windows.win_powershell:
        script: Get-ChildItem -Path D:\ -Force | Format-Table Mode, LastWriteTime, Length, Name -AutoSize
      register: result

    - name: Show output
      ansible.builtin.debug:
        var: result.stdout_lines
