---
- name: List D drive contents
  gather_facts: false
  hosts: "{{ target }}"
  tasks:
    - name: Get D drive contents
      ansible.windows.win_powershell: Get-ChildItem -Path D:\ -Force | Format-Table Mode, LastWriteTime, Length, Name -AutoSize
      register: result

    - name: Show output
      ansible.builtin.debug:
        var: result.stdout_lines
