---
collections:
  - name: community.hashi_vault
    version: ">=4.0.0"
  - name: ansible.windows
    version: ">=3.2.0"
  - name: amazon.aws
    version: ">=10.1.2"
  - name: community.windows
    version: ">=3.0.1"
  - name: community.crypto
    version: ">=2.17.0"
  - name: trippsc2.mssql
    version: ">=1.3.4"
  - name: community.general
    version: ">=11.4.1"
