---
- name: Connect to Windows host and print hostname
  hosts: aws_ec2
  gather_facts: false
  collections:
    - community.hashi_vault
  vars:
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_become: false
    vault_secret: "{{ lookup('community.hashi_vault.vault_kv2_get', 'windows/ssh/' + inventory_hostname, auth_method='approle', role_id=lookup('env', 'VAULT_ROLE_ID'), secret_id=lookup('env', 'VAULT_SECRET_ID'), url=lookup('env', 'VAULT_ADDR'), validate_certs=False) }}"
    ansible_user: Administrator
    ansible_ssh_pass: "{{ vault_secret.secret.admin_password }}"
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -vv'

  tasks:
    - name: Debug vault secret structure
      debug:
        var: vault_secret

    - name: Get Windows hostname
      win_shell: $env:COMPUTERNAME
      register: hostname_result

    - name: Display hostname
      debug:
        msg: "Windows hostname: {{ hostname_result.stdout | trim }}"

    - name: Clean up temporary private key file
      file:
        path: "/tmp/private_key_{{ inventory_hostname }}"
        state: absent
      connection: local