---
- name: Retrieve credentials from Vault
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - community.hashi_vault
  vars:
    vault_path: "windows/ssh/{{ target_host }}"
  
  tasks:
    - name: Retrieve SSH credentials from Vault
      community.hashi_vault.vault_kv2_get:
        path: "{{ vault_path }}"
      register: vault_secrets

    - name: Write private key to temporary file
      copy:
        content: "{{ vault_secrets.data.data.private_key }}"
        dest: "/tmp/private_key_{{ target_host }}"
        mode: '0600'

    - name: Set connection variables for all Windows hosts
      set_fact:
        ansible_user: Administrator
        ansible_ssh_private_key_file: "/tmp/private_key_{{ item }}"
        ansible_connection: ssh
        ansible_shell_type: powershell
        ansible_become: false
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['aws_ec2'] }}"

- name: Connect to Windows host and print hostname
  hosts: aws_ec2
  gather_facts: false

  tasks:
    - name: Get Windows hostname
      win_shell: $env:COMPUTERNAME
      register: hostname_result

    - name: Display hostname
      debug:
        msg: "Windows hostname: {{ hostname_result.stdout | trim }}"

    - name: Clean up temporary private key file
      file:
        path: "{{ ansible_ssh_private_key_file }}"
        state: absent
      connection: local